# Elixir CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  "elixir 1.11":
    parallelism: 1
    docker:
      - image: cimg/elixir:1.11-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mkdir ./tmp11
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix openfn.install.runtime
      - run: mix coveralls.json -o ./tmp11

      - store_test_results:
          path: ./tmp11

  "elixir 1.13":
    parallelism: 1
    docker:
      - image: cimg/elixir:1.13-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mkdir ./tmp13
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix openfn.install.runtime
      - run: mix coveralls.json -o ./tmp13

      - store_test_results:
          path: ./tmp13

workflows:
  version: 2
  "elixir 1.11":
    jobs:
      - "elixir 1.11"

  "elixir 1.13":
    jobs:
      - "elixir 1.13"
