# Elixir CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.11.3-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
      - run: source $HOME/.cargo/env
      - run: rust target add x86_64-pc-linux-gnu
      - run: mkdir ./tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix openfn.install.runtime
      - run: mix coveralls.json -o ./tmp

      - store_test_results:
          path: ./tmp