version: 2.1

commands:
  install_node:
    steps:
      - run:
          name: "Install Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v16.17.1/node-v16.17.1-linux-x64.tar.gz" | tar --strip-components=1 -xz -C /usr/local
      - run:
          name: Check current version of node
          command: node -v

jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/elixir:1.13.4-erlang-24.3-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: elixir --version
      - run: mkdir ./tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix openfn.install.runtime
      - run: mix coveralls.json -o ./tmp

      - store_test_results:
          path: ./tmp
