# Elixir CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.11.3-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mkdir ./tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do setup, deps.compile, compile
      - run: mix test