# Check https://circleci.com/docs/3.0/language-elixir/ for more details
version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/elixir:1.13.4-erlang-24.3-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mkdir ./tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix openfn.install.runtime
      - run: mix coveralls.json -o ./tmp

      - store_test_results:
          path: ./tmp